# Generated by Django 5.2.1 on 2025-05-22 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='status',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
